/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package lr10;
import java.nio.file.Files;
import java.io.FileReader;
import java.io.BufferedReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Scanner;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;


public class TableFrame extends javax.swing.JFrame {

    /**
     * Creates new form TableFrame
     */
    public TableFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Номер", "Ф.И.О", "Кафедра", "Степень", "Предмет", "IDE", "Исп.языки"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Загрузить  CSV");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Сохранить в JSON");
        jButton2.setActionCommand("Сохранить ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 622, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        
        try { 

            BufferedReader reader = new BufferedReader(new FileReader("list.csv")); 

            String line = null; 

            Scanner scanner = null; 

            int index = 0; 

            ArrayList<specialists> specList = new ArrayList<>(); 

            while ((line = reader.readLine()) != null) { 

                specialists spec = new specialists(); 

                scanner = new Scanner(line); 

                scanner.useDelimiter("%"); 

                while (scanner.hasNext()) { 

                    String data = scanner.next(); 

                    if (index == 0) 

                        spec.setId(Integer.parseInt(data)); 

                    else if (index == 1) spec.setFIO(data); 

                    else if (index == 2) 

                        spec.setDepartment(data); 

                    else if (index == 3) spec.setPower(data); 

                    else if (index == 4) spec.setTech(data); 

                    else if (index == 5) spec.setIDE(data); 

                    else if (index == 6) spec.setLang(data); 

                    else System.out.println("Ошибка: " + data); 

                    index++; } 

                index = 0; 

                specList.add(spec); } 

            reader.close(); 

            DefaultTableModel mod = (DefaultTableModel)jTable1.getModel();
            mod.setRowCount(0); // очистка таблицы

            Object[] row = new Object[7]; 

            for (int i=0; i<specList.size(); i++) { 

                row[0] = specList.get(i).getId(); 

                row[1] = specList.get(i).getFIO(); 

                row[2] = specList.get(i).getDepartment(); 

                row[3] = specList.get(i).getPower(); 

                row[4] = specList.get(i).getTech(); 

                row[5] = specList.get(i).getIDE(); 

                row[6] = specList.get(i).getLang(); 

                mod.addRow(row); } 

        } 

        catch (Exception e) { 

            JOptionPane.showMessageDialog(null, e); } 
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        JSONObject obj = new JSONObject(); 

        obj.put("Подразделение", "Кафедра ИС"); 

        JSONArray list = new JSONArray(); 

        list.clear(); 

        for (int i=0; i<jTable1.getRowCount(); i++) { 

            JSONObject spec = new JSONObject(); 

            spec.put("id", jTable1.getValueAt(i, 0)); 

            spec.put("fio", jTable1.getValueAt(i, 1)); 

            spec.put("department", jTable1.getValueAt(i, 2)); 

            spec.put("power", jTable1.getValueAt(i, 3)); 

            spec.put("tech", jTable1.getValueAt(i, 4)); 

            spec.put("ide", jTable1.getValueAt(i, 5)); 

            spec.put("lang", jTable1.getValueAt(i, 6)); 

            list.add(spec); 

        } 

        obj.put("specialists", list); 

        try (FileWriter jsonfile = new FileWriter("list.json")) { 

            jsonfile.write(obj.toJSONString()); 

            jsonfile.flush(); 

        } catch(IOException e) {e.printStackTrace();} 
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TableFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TableFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TableFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TableFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TableFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
