/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.Dimension;
import java.awt.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.HeadlessException; 
import java.sql.*; 
import net.proteanit.sql.DbUtils; 
import javax.swing.JOptionPane; 
import java.awt.event.*;
import javax.swing.table.TableRowSorter;
/**
 *
 * @author Artem
 */
public class UsersFrame extends javax.swing.JFrame {
    Connection con = null; 
    PreparedStatement pst = null; 
    ResultSet rs = null; 
    public String[] elements = {"Мужской", "Женский"};
    JComboBox editComboBox = new JComboBox(elements);

    JComboBox listtext = new JComboBox(elements);
    
    /**
     * Creates new form UsersFrame
     */
    public UsersFrame() {
        initComponents();
        show_users();
        TableColorCellRenderer renderer = new TableColorCellRenderer(); 
        jTable1.setDefaultRenderer(Object.class, renderer); 
        
        
        
    }
    
  public ArrayList<Users> usersList() { 

        ArrayList<Users> usersList = new ArrayList<>(); 

        try { 

            Connection con = DriverManager.getConnection("jdbc:sqlserver://localhost\\DESKTOP-8QUV2V6\\SQLEXPRESS:1433;databaseName=test","igorg","igorg"); 

            String sql = "select * from users"; 

            Statement st = con.createStatement(); 

            ResultSet rs = st.executeQuery(sql); 

            Users users; 

            while (rs.next()) { 

                users = new Users(rs.getInt("id"), rs.getString("fio"), rs.getString("staff"), rs.getString("tel"), rs.getString("login"), rs.getString("pass"), rs.getString("sex")); 

                usersList.add(users); 

            } 

        } 

        catch (Exception e) { 

            JOptionPane.showMessageDialog(null, e); 

        } 

        return usersList; 

    }   
public void show_users() { 

        ArrayList<Users> list = usersList(); 

        DefaultTableModel mod = (DefaultTableModel)jTable1.getModel(); 

        Object[] col = new Object[7]; 

        for (int i=0; i<list.size(); i++) { 

            col[0] = list.get(i).getid(); 

            col[1] = list.get(i).getfio(); 

            col[2] = list.get(i).getstaff(); 

            col[3] = list.get(i).gettel(); 

            col[4] = list.get(i).getlogin(); 

            col[5] = list.get(i).getpass(); 

            col[6] = list.get(i).getsex(); 

            mod.addRow(col); 

        } 

    } 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<String>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jTextField5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Номер", "ФИО пользователя", "Должность", "Телефон", "Логин", "Пароль", "Пол"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Ф.И.О:");

        jLabel2.setText("Должность:");

        jLabel3.setText("Телефон:");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel4.setText("Логин:");

        jLabel5.setText("Пароль:");

        jLabel6.setText("Пол:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Мужской ", "Женский" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jButton1.setText("Добавить");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Изменить");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Удалить");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTextField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField5KeyReleased(evt);
            }
        });

        jLabel7.setText("Поиск по фамилии:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 701, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                            .addComponent(jTextField2)
                            .addComponent(jTextField1)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField4))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1)
                        .addComponent(jButton2)
                        .addComponent(jButton3))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try { 

            Connection con = DriverManager.getConnection("jdbc:sqlserver://localhost\\DESKTOP-8QUV2V6\\SQLEXPRESS:1433;databaseName=test","igorg","igorg"); 

            String sql = "insert into users (fio, staff, tel, login, pass, sex) values (?,?,?,?,?,?)"; 

            PreparedStatement pst = con.prepareStatement(sql); 

            pst.setString (1, jTextField1.getText()); 

            pst.setString (2, jTextField2.getText()); 

            pst.setString (3, jTextField3.getText()); 

            pst.setString (4, jTextField4.getText()); 

            pst.setString (5, jPasswordField1.getText()); 

            pst.setString (6, jComboBox1.getSelectedItem().toString()); 

            pst.executeUpdate(); 

            JOptionPane.showMessageDialog(null, "Inserted!"); 

            con.close(); 

            show_users(); 

        }  

        catch (Exception e) { 

            JOptionPane.showMessageDialog(null, e); 

        } 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
         DefaultTableModel tblmod = (DefaultTableModel)jTable1.getModel(); 

        String tbl_fio = tblmod.getValueAt(jTable1.getSelectedRow(), 1).toString(); 

        String tbl_staff = tblmod.getValueAt(jTable1.getSelectedRow(), 2).toString(); 

        String tbl_tel = tblmod.getValueAt(jTable1.getSelectedRow(), 3).toString(); 

        String tbl_login = tblmod.getValueAt(jTable1.getSelectedRow(), 4).toString(); 

        String tbl_pass = tblmod.getValueAt(jTable1.getSelectedRow(), 5).toString(); 

        String tbl_sex = tblmod.getValueAt(jTable1.getSelectedRow(), 6).toString(); 

        jTextField1.setText(tbl_fio); 

        jTextField2.setText(tbl_staff); 

        jTextField3.setText(tbl_tel); 

        jTextField4.setText(tbl_login); 

        jPasswordField1.setText(tbl_pass); 

        jComboBox1.setSelectedItem(tbl_sex); 
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try { 

            String sql = "delete from users where id =?"; 
            
            DefaultTableModel tblmod = (DefaultTableModel)jTable1.getModel();
             
            con = DriverManager.getConnection("jdbc:sqlserver://localhost\\DESKTOP-8QUV2V6\\SQLEXPRESS:1433;databaseName=test","igorg","igorg"); 

            pst = con.prepareStatement(sql); 

            pst.setString(1, tblmod.getValueAt(jTable1.getSelectedRow(), 0).toString());

            pst.executeUpdate(); 

            JOptionPane.showMessageDialog(null, "The data deleted!"); 

        } catch (SQLException | HeadlessException ex) { 

            JOptionPane.showMessageDialog(null, ex); } 

        showDataTable(); 
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        DefaultTableModel tblmod = (DefaultTableModel)jTable1.getModel(); 

        if (jTable1.getSelectedRowCount() == 1) { 

            try { 

                String sql = "update users set fio=?, staff=?, tel=?, login=?, pass=?, sex=? where id =?"; 

                Connection con = DriverManager.getConnection("jdbc:sqlserver://localhost\\DESKTOP-8QUV2V6\\SQLEXPRESS:1433;databaseName=test","igorg","igorg"); 

                PreparedStatement pst = con.prepareStatement(sql); 

                pst.setString(1, jTextField1.getText()); 

                pst.setString(2, jTextField2.getText()); 

                pst.setString(3, jTextField3.getText()); 

                pst.setString(4, jTextField4.getText()); 

                pst.setString(5, jPasswordField1.getText()); 

                pst.setString(6, jComboBox1.getSelectedItem().toString()); 

                pst.setString(7, tblmod.getValueAt(jTable1.getSelectedRow(), 0).toString()); 

                pst.executeUpdate(); 

                DefaultTableModel mod = (DefaultTableModel)jTable1.getModel(); 

                mod.setRowCount(0); 

                show_users(); 

            } catch (SQLException | HeadlessException ex) { 

                JOptionPane.showMessageDialog(null, ex); } 

            JOptionPane.showMessageDialog(null, "The data updated!"); 

        } else { if (jTable1.getSelectedRowCount() == 0) 

                JOptionPane.showMessageDialog(null, "The string is not selected!"); 

            else { JOptionPane.showMessageDialog(null, "Select single string for update!"); } 

        } 
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextField5KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyReleased
        filter(jTextField5.getText());
    }//GEN-LAST:event_jTextField5KeyReleased

    private void filter(String str) { 

        DefaultTableModel mod = (DefaultTableModel)jTable1.getModel(); 

        TableRowSorter<DefaultTableModel> tr = new TableRowSorter <DefaultTableModel> (mod); 

        jTable1.setRowSorter(tr); 

        tr.setRowFilter(RowFilter.regexFilter(str, 1)); 

    } 
    
      public void showDataTable() {
        try {
            Connection con = DriverManager.getConnection("jdbc:sqlserver://localhost\\DESKTOP-8QUV2V6\\SQLEXPRESS:1433;databaseName=test","igorg","igorg");
            String sql = "select * from users order by id";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs)); }
        catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex); }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        
        
        
        
        
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UsersFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UsersFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UsersFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UsersFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UsersFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
