/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.Dimension;
import java.awt.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.util.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.HeadlessException; 
import java.sql.*; 
import net.proteanit.sql.DbUtils; 
import javax.swing.JOptionPane; 
import java.awt.event.*;
import javax.swing.table.TableRowSorter;
/**
 *
 * @author Artem
 */
public class OrdersFrame extends javax.swing.JFrame {
     Connection connect = null; 

     PreparedStatement pst = null; 

     ResultSet rs = null;    
    /**
     * Creates new form OrdersFrame
     */
    public OrdersFrame() {
        initComponents();
        show_orders();
    }
    
    public ArrayList<Orders> ordersList() { 

        ArrayList<Orders> ordersList = new ArrayList<>(); 

        try { 

            Connection con = DriverManager.getConnection("jdbc:sqlserver://localhost\\DESKTOP-8QUV2V6\\SQLEXPRESS:1433;databaseName=test","igorg","igorg"); 

            String sql = "select * from orderr"; 

            Statement st = con.createStatement(); 

            ResultSet rs = st.executeQuery(sql); 

            Orders orders; 

            while (rs.next()) { 

                orders = new Orders(rs.getInt("id"), rs.getString("orderr"), rs.getInt("department"), rs.getString("datee"), rs.getInt("acceptor"), rs.getString("status")); 

                ordersList.add(orders); 

            } 

        } 

        catch (Exception e) { 

            JOptionPane.showMessageDialog(null, e); 

        } 

        return ordersList; 

    }   
    
    public void show_orders() { 

        ArrayList<Orders> list = ordersList(); 

        DefaultTableModel mod = (DefaultTableModel)jTable1.getModel(); 

        Object[] col = new Object[6]; 

        for (int i=0; i<list.size(); i++) { 

            col[0] = list.get(i).getid(); 

            col[1] = list.get(i).getOrder(); 

            col[2] = list.get(i).getDepartment(); 

            col[3] = list.get(i).getDate(); 

            col[4] = list.get(i).getAcceptor(); 

            col[5] = list.get(i).getStatus(); 
            mod.addRow(col); 

        } 

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jTextField6 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Номер", "Заказ", "Код отдела", "Дата заказа", "Код получателя", "Статус"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Заказ:");

        jLabel2.setText("Отдел:");

        jLabel3.setText("Дата заказа:");

        jLabel4.setText("Получатель:");

        jLabel5.setText("Статус:");

        jButton1.setText("Добавить");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Изменить");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Удалить");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTextField6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField6KeyReleased(evt);
            }
        });

        jLabel6.setText("Поиск:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(29, 29, 29)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2))
                            .addGap(41, 41, 41)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                                .addComponent(jTextField2)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(41, 41, 41)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField6, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTextField4)
                        .addComponent(jTextField5, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)))
                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(0, 44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         try { 

            Connection con = DriverManager.getConnection("jdbc:sqlserver://localhost\\DESKTOP-8QUV2V6\\SQLEXPRESS:1433;databaseName=test","igorg","igorg"); 

            String sql = "insert into orderr (orderr, department, datee, acceptor, status) values (?,?,?,?,?)"; 

            PreparedStatement pst = con.prepareStatement(sql); 

            pst.setString (1, jTextField1.getText()); 

            pst.setString (2, jTextField2.getText()); 

            pst.setString (3, jTextField3.getText()); 

            pst.setString (4, jTextField4.getText()); 

            pst.setString (5, jTextField5.getText()); 

            pst.executeUpdate(); 

            JOptionPane.showMessageDialog(null, "Inserted!"); 

            con.close(); 

            show_orders(); 

        }  

        catch (Exception e) { 

            JOptionPane.showMessageDialog(null, e); 

        } 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        DefaultTableModel tblmod = (DefaultTableModel)jTable1.getModel(); 

        if (jTable1.getSelectedRowCount() == 1) { 

            try { 

                String sql = "update orderr set orderr=?, department=?, datee=?, acceptor=?, status=? where id =?"; 

                Connection con = DriverManager.getConnection("jdbc:sqlserver://localhost\\DESKTOP-8QUV2V6\\SQLEXPRESS:1433;databaseName=test","igorg","igorg"); 

                PreparedStatement pst = con.prepareStatement(sql); 

                pst.setString(1, jTextField1.getText()); 

                pst.setString(2, jTextField2.getText()); 

                pst.setString(3, jTextField3.getText()); 

                pst.setString(4, jTextField4.getText()); 

                pst.setString(5, jTextField5.getText()); 

                pst.setString(6, tblmod.getValueAt(jTable1.getSelectedRow(), 0).toString()); 

                pst.executeUpdate(); 

                DefaultTableModel mod = (DefaultTableModel)jTable1.getModel(); 

                mod.setRowCount(0); 

                show_orders(); 

            } catch (SQLException | HeadlessException ex) { 

                JOptionPane.showMessageDialog(null, ex); } 

            JOptionPane.showMessageDialog(null, "The data updated!"); 

        } else { if (jTable1.getSelectedRowCount() == 0) 

                JOptionPane.showMessageDialog(null, "The string is not selected!"); 

            else { JOptionPane.showMessageDialog(null, "Select single string for update!"); } 

        } 
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try { 

            String sql = "delete from orderr where id =?"; 
            
            DefaultTableModel tblmod = (DefaultTableModel)jTable1.getModel();
             
            connect = DriverManager.getConnection("jdbc:sqlserver://localhost\\DESKTOP-8QUV2V6\\SQLEXPRESS:1433;databaseName=test","igorg","igorg"); 

            pst = connect.prepareStatement(sql); 

            pst.setString(1, tblmod.getValueAt(jTable1.getSelectedRow(), 0).toString());

            pst.executeUpdate(); 

            JOptionPane.showMessageDialog(null, "The data deleted!"); 

        } catch (SQLException | HeadlessException ex) { 

            JOptionPane.showMessageDialog(null, ex); } 

        showDataTable(); 
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        DefaultTableModel tblmod = (DefaultTableModel)jTable1.getModel(); 

        String tbl_orderr = tblmod.getValueAt(jTable1.getSelectedRow(), 1).toString(); 

        String tbl_department = tblmod.getValueAt(jTable1.getSelectedRow(), 2).toString(); 

        String tbl_datee = tblmod.getValueAt(jTable1.getSelectedRow(), 3).toString(); 

        String tbl_acceptor = tblmod.getValueAt(jTable1.getSelectedRow(), 4).toString(); 

        String tbl_status = tblmod.getValueAt(jTable1.getSelectedRow(), 5).toString(); 


        jTextField1.setText(tbl_orderr); 

        jTextField2.setText(tbl_department); 

        jTextField3.setText(tbl_datee); 

        jTextField4.setText(tbl_acceptor); 

        jTextField5.setText(tbl_status); 

    }//GEN-LAST:event_jTable1MouseClicked

    private void jTextField6KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField6KeyReleased
        filter(jTextField6.getText()); 
    }//GEN-LAST:event_jTextField6KeyReleased
 public void showDataTable() {
        try {
            Connection con = DriverManager.getConnection("jdbc:sqlserver://localhost\\DESKTOP-8QUV2V6\\SQLEXPRESS:1433;databaseName=test","igorg","igorg");
            String sql = "select * from orderr order by id";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs)); }
        catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex); }
    }
 
 private void filter(String str) { 

        DefaultTableModel mod = (DefaultTableModel)jTable1.getModel(); 

        TableRowSorter<DefaultTableModel> tr = new TableRowSorter <DefaultTableModel> (mod); 
   
        jTable1.setRowSorter(tr); 
        tr.setRowFilter(RowFilter.regexFilter(str, 1,2,3,4,5));
        
    } 
 
 
 
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrdersFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrdersFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrdersFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrdersFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrdersFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
